const app=document.getElementById('app');let page='dashboard',dash;
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'حدث خطأ');return d}
function login(){app.innerHTML=`<div class="login"><form class="card" id="login"><div class="brand">VIP</div><p class="muted">نظام إدارة مغسلة VIP</p><label>اسم المستخدم</label><input class="input" name="username" value="admin" required><label>كلمة المرور</label><input class="input" name="password" type="password" value="1234" required><button class="btn red">تسجيل الدخول</button><p class="muted">الدخول الأول: admin / 1234</p></form></div>`;login.onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}catch(x){alert(x.message)}}}
const pages={dashboard:'لوحة التحكم',customers:'العملاء',invoices:'الفواتير',products:'المخزون',services:'خدمات الغسيل',employees:'الموظفون',carpets:'غسيل السجاد',expenses:'المصروفات',reports:'التقارير',settings:'الإعدادات'};
async function render(){try{dash=await api('/api/dashboard')}catch(e){return login()}app.innerHTML=`<div class="shell"><aside class="side"><h1>VIP</h1><div class="nav">${Object.entries(pages).map(([k,v])=>`<button class="${page===k?'active':''}" data-p="${k}">${v}</button>`).join('')}</div></aside><main class="main"><div class="top"><div><h2>${pages[page]}</h2><span class="muted">نظام إدارة وتشغيل VIP</span></div><button class="btn red" id="new">+ فاتورة جديدة</button></div><section id="content"></section></main></div>`;document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{page=b.dataset.p;render()});document.getElementById('new').onclick=newInvoice;draw()}
async function draw(){const c=document.getElementById('content');if(page==='dashboard'){c.innerHTML=`<div class="grid"><div class="stat">إيرادات اليوم<b>${dash.sales.total} ج</b></div><div class="stat">فواتير اليوم<b>${dash.sales.count}</b></div><div class="stat">عمليات الغسيل<b>${dash.vehicles}</b></div><div class="stat">طلبات السجاد<b>${dash.carpets}</b></div></div><div class="panel"><h3>تنبيهات المخزون</h3>${dash.alerts.length?dash.alerts.map(x=>`<div class="alert ${x.stock<=0?'danger':''}">${x.name} — المتاح ${x.stock} — الحد ${x.min_stock}</div>`).join(''):'لا توجد تنبيهات'}</div>`}
else if(page==='customers'){const a=await api('/api/customers');c.innerHTML=`<div class="panel"><form id="f"><div class="row"><div><label>اسم العميل</label><input class="input" name="name" required></div><div><label>الهاتف</label><input class="input" name="phone"></div><button class="btn">إضافة</button></div></form></div><div class="panel"><table class="table"><tr><th>الكود</th><th>الاسم</th><th>الهاتف</th></tr>${a.map(x=>`<tr><td>${x.code}</td><td>${x.name}</td><td>${x.phone||'-'}</td></tr>`).join('')}</table></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/customers',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}}
else if(page==='products'){const a=await api('/api/products');c.innerHTML=`<div class="panel"><form id="f"><div class="row"><select class="input" name="section"><option value="oil">الزيوت</option><option value="cafeteria">الكافتيريا</option></select><input class="input" name="name" placeholder="اسم المنتج" required><input class="input" name="purchase_price" type="number" placeholder="سعر الشراء"><input class="input" name="selling_price" type="number" placeholder="سعر البيع"><input class="input" name="stock" type="number" placeholder="المخزون"><input class="input" name="min_stock" type="number" value="3" placeholder="الحد الأدنى"><button class="btn">إضافة منتج</button></div></form></div><div class="panel"><table class="table"><tr><th>القسم</th><th>المنتج</th><th>شراء</th><th>بيع</th><th>المخزون</th></tr>${a.map(x=>`<tr><td>${x.section==='oil'?'الزيوت':'الكافتيريا'}</td><td>${x.name}</td><td>${x.purchase_price}</td><td>${x.selling_price}</td><td>${x.stock}</td></tr>`).join('')}</table></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/products',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}}
else if(page==='services'){const a=await api('/api/services');c.innerHTML=`<div class="panel"><form id="f"><div class="row"><input class="input" name="name" placeholder="اسم الخدمة" required><input class="input" name="price" type="number" placeholder="السعر"><button class="btn">إضافة خدمة</button></div></form></div><div class="panel"><table class="table"><tr><th>الخدمة</th><th>السعر</th></tr>${a.map(x=>`<tr><td>${x.name}</td><td>${x.price}</td></tr>`).join('')}</table></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/services',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}}
else if(page==='employees'){const a=await api('/api/employees');c.innerHTML=`<div class="panel"><form id="f"><div class="row"><input class="input" name="name" placeholder="اسم الموظف" required><input class="input" name="phone" placeholder="الهاتف"><input class="input" name="job" placeholder="الوظيفة"><button class="btn">إضافة</button></div></form></div><div class="panel"><table class="table"><tr><th>الاسم</th><th>الهاتف</th><th>الوظيفة</th><th>الحالة</th></tr>${a.map(x=>`<tr><td>${x.name}</td><td>${x.phone}</td><td>${x.job}</td><td>${x.status}</td></tr>`).join('')}</table></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/employees',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}}
else if(page==='invoices'){const a=await api('/api/invoices');c.innerHTML=`<div class="panel"><table class="table"><tr><th>رقم</th><th>القسم</th><th>العميل</th><th>الإجمالي</th><th>الدفع</th><th>التاريخ</th></tr>${a.map(x=>`<tr><td>${x.number}</td><td>${x.section}</td><td>${x.customer_name||'-'}</td><td>${x.total} ج</td><td>${x.payment_method==='cash'?'كاش':'InstaPay'}</td><td>${x.created_at}</td></tr>`).join('')}</table></div>`}
else if(page==='expenses'){const a=await api('/api/expenses');c.innerHTML=`<div class="panel"><form id="f"><div class="row"><input class="input" name="category" placeholder="بند المصروف" required><input class="input" name="amount" type="number" placeholder="المبلغ" required><input class="input" name="description" placeholder="البيان"><select class="input" name="payment_method"><option value="cash">كاش</option><option value="instapay">InstaPay</option></select><button class="btn">حفظ</button></div></form></div><div class="panel"><table class="table"><tr><th>البند</th><th>المبلغ</th><th>البيان</th><th>الدفع</th></tr>${a.map(x=>`<tr><td>${x.category}</td><td>${x.amount}</td><td>${x.description}</td><td>${x.payment_method}</td></tr>`).join('')}</table></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/expenses',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}}
else if(page==='reports'){const r=await api('/api/reports');c.innerHTML=`<div class="panel"><h3>تقرير اليوم</h3>${r.sections.map(x=>`<p>${x.section}: ${x.revenue} ج — ${x.invoices} فاتورة</p>`).join('')||'<p>لا توجد مبيعات</p>'}<p><b>المصروفات:</b> ${r.expenses} ج</p></div>`}
else if(page==='settings'){const s=await api('/api/settings'),m=Object.fromEntries(s.map(x=>[x.k,x.v]));c.innerHTML=`<div class="panel"><h3>ترقيم النظام</h3><form id="f"><div class="row"><input class="input" name="customer_start" type="number" min="1" value="${m.customer_start||1}"><input class="input" name="invoice_start" type="number" min="1" value="${m.invoice_start||1}"><button class="btn">حفظ</button></div></form><p class="muted">أكواد العملاء والفواتير مستقلة وتبدأ من الرقم الذي تحدده، مع منع التكرار.</p></div>`;f.onsubmit=async e=>{e.preventDefault();await api('/api/settings',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert('تم الحفظ');render()}}
else if(page==='carpets'){c.innerHTML=`<div class="panel"><h3>غسيل السجاد</h3><p>الفئات: سجاد — حفظات — مشايات</p><p class="muted">الفاتورة الواحدة يمكن أن تحتوي على عدة قطع، ويتم حساب المساحة والإجمالي تلقائيًا عند إنشاء الفاتورة.</p><button class="btn red" onclick="newInvoice()">إنشاء فاتورة سجاد</button></div>`}}
async function newInvoice(){const section=prompt('القسم: wash / carpet / oil / cafeteria','wash');if(!section)return;const desc=prompt('الخدمة أو المنتج','غسيل كامل');const price=Number(prompt('السعر','0')||0);const payment=prompt('الدفع: cash أو instapay','cash');try{const r=await api('/api/invoices',{method:'POST',body:JSON.stringify({section,items:[{description:desc,qty:1,unit_price:price,meta:section==='wash'?{vehicle:true}:{}}],payment_method:payment==='instapay'?'instapay':'cash'})});alert('تم إنشاء الفاتورة رقم '+r.number+' بإجمالي '+r.total+' ج');render()}catch(e){alert(e.message)}}
render();
