const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');
const PORT=process.env.PORT||3000, DBPATH=process.env.DB_PATH||path.join(__dirname,'data','vip.sqlite');
fs.mkdirSync(path.dirname(DBPATH),{recursive:true}); const db=new DatabaseSync(DBPATH);
function exec(sql,p=[]){return db.prepare(sql).run(...p)} function all(sql,p=[]){return db.prepare(sql).all(...p)} function one(sql,p=[]){return db.prepare(sql).get(...p)}
exec(`PRAGMA foreign_keys=ON`);
exec(`CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT NOT NULL)`);exec(`CREATE TABLE IF NOT EXISTS seq(k TEXT PRIMARY KEY,n INTEGER NOT NULL)`);
exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE,password_hash TEXT,role TEXT DEFAULT 'manager')`);
exec(`CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,code INTEGER UNIQUE,name TEXT NOT NULL,phone TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
exec(`CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,job TEXT,status TEXT DEFAULT 'active')`);
exec(`CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,price REAL DEFAULT 0,active INTEGER DEFAULT 1)`);
exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,section TEXT NOT NULL,name TEXT NOT NULL,code TEXT,brand TEXT,purchase_price REAL DEFAULT 0,selling_price REAL DEFAULT 0,stock REAL DEFAULT 0,min_stock REAL DEFAULT 3,active INTEGER DEFAULT 1)`);
exec(`CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,number INTEGER UNIQUE,section TEXT,customer_id INTEGER,subtotal REAL,discount REAL,total REAL,payment_method TEXT,status TEXT DEFAULT 'paid',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id))`);
exec(`CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER,description TEXT,qty REAL,unit_price REAL,cost_price REAL,employee_id INTEGER,meta TEXT,FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE)`);
exec(`CREATE TABLE IF NOT EXISTS carpet_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER UNIQUE,customer_id INTEGER,status TEXT DEFAULT 'received',FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE)`);
exec(`CREATE TABLE IF NOT EXISTS carpet_items(id INTEGER PRIMARY KEY AUTOINCREMENT,carpet_order_id INTEGER,category TEXT,quantity REAL,length REAL,width REAL,area REAL,meter_price REAL,total REAL,FOREIGN KEY(carpet_order_id) REFERENCES carpet_orders(id) ON DELETE CASCADE)`);
exec(`CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,category TEXT,section TEXT,amount REAL,description TEXT,payment_method TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
exec(`CREATE TABLE IF NOT EXISTS inventory_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,movement_type TEXT,quantity REAL,reference TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
for(const [k,v] of [['customer_start','1'],['invoice_start','1']]) exec(`INSERT OR IGNORE INTO settings(k,v) VALUES(?,?)`,[k,v]);
for(const [k,v] of [['customer','1'],['invoice','1']]) exec(`INSERT OR IGNORE INTO seq(k,n) VALUES(?,?)`,[k,v]);
function hash(p){return crypto.createHash('sha256').update('VIP:'+p).digest('hex')}
if(!one('SELECT id FROM users WHERE username=?',['admin'])) exec('INSERT INTO users(username,password_hash) VALUES(?,?)',['admin',hash('1234')]);
if(!one('SELECT id FROM services LIMIT 1')) for(const x of [['غسيل كامل',0],['غسيل نصف',0],['رش',0],['مياه وصابون',0]]) exec('INSERT INTO services(name,price) VALUES(?,?)',x);
const sessions=new Map();
function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(data))}
function read(req){return new Promise((ok,no)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){no(e)}})})}
function auth(req){const c=req.headers.cookie||'',m=c.match(/vip_session=([^;]+)/);return m&&sessions.has(m[1])}
function nextNum(k){const r=one('SELECT n FROM seq WHERE k=?',[k]);const n=r.n;exec('UPDATE seq SET n=n+1 WHERE k=?',[k]);return n}
function customerCode(){let n=nextNum('customer');const m=one('SELECT MAX(code) m FROM customers');if(m&&m.m!=null&&n<=m.m)n=m.m+1;exec('UPDATE seq SET n=? WHERE k=?',[n+1,'customer']);return n}
function invoiceNum(){let n=nextNum('invoice');const m=one('SELECT MAX(number) m FROM invoices');if(m&&m.m!=null&&n<=m.m)n=m.m+1;exec('UPDATE seq SET n=? WHERE k=?',[n+1,'invoice']);return n}
async function api(req,res,u){try{
if(req.method==='POST'&&u.pathname==='/api/login'){const b=await read(req),x=one('SELECT * FROM users WHERE username=?',[b.username||'']);if(!x||x.password_hash!==hash(b.password||''))return json(res,401,{error:'اسم المستخدم أو كلمة المرور غير صحيحة'});const s=crypto.randomBytes(24).toString('hex');sessions.set(s,{uid:x.id});return json(res,200,{ok:true},{'Set-Cookie':`vip_session=${s}; HttpOnly; SameSite=Lax; Path=/`})}
if(u.pathname.startsWith('/api/')&&!auth(req))return json(res,401,{error:'يجب تسجيل الدخول'});
if(u.pathname==='/api/dashboard'){const sales=one(`SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM invoices WHERE date(created_at)=date('now','localtime')`);const vehicles=one(`SELECT COUNT(*) count FROM invoice_items WHERE date((SELECT created_at FROM invoices WHERE id=invoice_items.invoice_id))=date('now','localtime') AND meta LIKE '%vehicle%'`);const carpets=one(`SELECT COUNT(*) count FROM carpet_orders WHERE date((SELECT created_at FROM invoices WHERE id=carpet_orders.invoice_id))=date('now','localtime')`);const alerts=all('SELECT * FROM products WHERE active=1 AND stock<=min_stock ORDER BY stock,name');return json(res,200,{sales,vehicles:vehicles.count,carpets:carpets.count,alerts})}
if(u.pathname==='/api/customers'&&req.method==='GET')return json(res,200,all('SELECT * FROM customers ORDER BY code'));if(u.pathname==='/api/customers'&&req.method==='POST'){const b=await read(req),code=customerCode();return json(res,201,one('INSERT INTO customers(code,name,phone) VALUES(?,?,?) RETURNING *',[code,b.name,b.phone||null]))}
if(u.pathname==='/api/employees'&&req.method==='GET')return json(res,200,all('SELECT * FROM employees ORDER BY name'));if(u.pathname==='/api/employees'&&req.method==='POST'){const b=await read(req);return json(res,201,one('INSERT INTO employees(name,phone,job,status) VALUES(?,?,?,?) RETURNING *',[b.name,b.phone||'',b.job||'',b.status||'active']))}
if(u.pathname==='/api/services'&&req.method==='GET')return json(res,200,all('SELECT * FROM services WHERE active=1 ORDER BY id'));if(u.pathname==='/api/services'&&req.method==='POST'){const b=await read(req);return json(res,201,one('INSERT INTO services(name,price) VALUES(?,?) RETURNING *',[b.name,b.price||0]))}
if(u.pathname==='/api/products'&&req.method==='GET')return json(res,200,all('SELECT * FROM products WHERE active=1 ORDER BY section,name'));if(u.pathname==='/api/products'&&req.method==='POST'){const b=await read(req);return json(res,201,one('INSERT INTO products(section,name,code,brand,purchase_price,selling_price,stock,min_stock) VALUES(?,?,?,?,?,?,?,?) RETURNING *',[b.section,b.name,b.code||'',b.brand||'',+b.purchase_price||0,+b.selling_price||0,+b.stock||0,+b.min_stock||3]))}
if(u.pathname==='/api/invoices'&&req.method==='GET')return json(res,200,all('SELECT i.*,c.name customer_name FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ORDER BY i.id DESC LIMIT 300'));
if(u.pathname==='/api/invoices'&&req.method==='POST'){const b=await read(req);db.exec('BEGIN');try{const num=invoiceNum(),items=b.items||[],sub=items.reduce((s,x)=>s+(+x.qty||1)*(+x.unit_price||0),0),discount=+b.discount||0,total=Math.max(0,sub-discount);const inv=one('INSERT INTO invoices(number,section,customer_id,subtotal,discount,total,payment_method,status) VALUES(?,?,?,?,?,?,?,?) RETURNING id',[num,b.section||'wash',b.customer_id||null,sub,discount,total,b.payment_method||'cash','paid']);for(const x of items){exec('INSERT INTO invoice_items(invoice_id,description,qty,unit_price,cost_price,employee_id,meta) VALUES(?,?,?,?,?,?,?)',[inv.id,x.description||'',+x.qty||1,+x.unit_price||0,+x.cost_price||0,x.employee_id||null,JSON.stringify(x.meta||{})]);if(x.product_id){const p=one('SELECT * FROM products WHERE id=?',[x.product_id]);exec('UPDATE products SET stock=stock-? WHERE id=?',[+x.qty||1,x.product_id]);exec('INSERT INTO inventory_movements(product_id,movement_type,quantity,reference) VALUES(?,?,?,?)',[x.product_id,'out',''+(+x.qty||1),'invoice:'+num])}}
if(b.section==='carpet'){const co=one('INSERT INTO carpet_orders(invoice_id,customer_id,status) VALUES(?,?,?) RETURNING id',[inv.id,b.customer_id||null,b.status||'received']);for(const x of b.carpet_items||[]){const area=(+x.length||0)*(+x.width||0)*(+x.quantity||1),tot=area*(+x.meter_price||0);exec('INSERT INTO carpet_items(carpet_order_id,category,quantity,length,width,area,meter_price,total) VALUES(?,?,?,?,?,?,?,?)',[co.id,x.category,+x.quantity||1,+x.length||0,+x.width||0,area,+x.meter_price||0,tot])}}db.exec('COMMIT');return json(res,201,{number:num,total})}catch(e){db.exec('ROLLBACK');throw e}}
if(u.pathname==='/api/expenses'&&req.method==='GET')return json(res,200,all('SELECT * FROM expenses ORDER BY id DESC LIMIT 300'));if(u.pathname==='/api/expenses'&&req.method==='POST'){const b=await read(req);return json(res,201,one('INSERT INTO expenses(category,section,amount,description,payment_method) VALUES(?,?,?,?,?) RETURNING *',[b.category,b.section||'',+b.amount||0,b.description||'',b.payment_method||'cash']))}
if(u.pathname==='/api/reports'){const from=u.searchParams.get('from')||new Date().toISOString().slice(0,10),to=u.searchParams.get('to')||from;const sections=all(`SELECT section,COUNT(*) invoices,COALESCE(SUM(total),0) revenue FROM invoices WHERE date(created_at) BETWEEN ? AND ? GROUP BY section ORDER BY section`,[from,to]);const expenses=one(`SELECT COALESCE(SUM(amount),0) expenses FROM expenses WHERE date(created_at) BETWEEN ? AND ?`,[from,to]);return json(res,200,{sections,expenses:expenses.expenses})}
if(u.pathname==='/api/settings'&&req.method==='GET')return json(res,200,all('SELECT * FROM settings ORDER BY k'));if(u.pathname==='/api/settings'&&req.method==='PUT'){const b=await read(req);for(const k of ['customer_start','invoice_start'])if(b[k]!=null){const key=k==='customer_start'?'customer':'invoice',table=k==='customer_start'?'customers':'invoices',col=k==='customer_start'?'code':'number',max=one(`SELECT COALESCE(MAX(${col}),0) m FROM ${table}`).m,n=Math.max(+b[k],max+1);exec('UPDATE settings SET v=? WHERE k=?',[String(b[k]),k]);exec('UPDATE seq SET n=? WHERE k=?',[n,key])}return json(res,200,{ok:true})}
return json(res,404,{error:'المسار غير موجود'})
}catch(e){console.error(e);return json(res,500,{error:e.message})}}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return api(req,res,u);let p=u.pathname==='/'?'/index.html':u.pathname;const f=path.join(__dirname,'public',decodeURIComponent(p));if(!fs.existsSync(f)||!fs.statSync(f).isFile())return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}).listen(PORT,()=>console.log(`VIP Web يعمل على http://localhost:${PORT}`));
